name: esoft

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - GO_ENV=production
    restart: always
    ports:
      - "$PORT:80"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./sql_scripts:/sql_scripts

  adminer:
    image: adminer
    ports:
        - "8082:8080"
    environment:
       ADMINER_DEFAULT_SERVER: db
    depends_on:
       - db

volumes:
  postgres_volume:
