definitions:
  domain.Agent:
    properties:
      commissionShare:
        type: integer
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      middleName:
        type: string
    type: object
  domain.Client:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      middleName:
        type: string
      phoneNumber:
        type: string
    type: object
  domain.ErrorMessage:
    properties:
      body:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /agents:
    delete:
      consumes:
      - application/json
      parameters:
      - description: scheme of agent
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Agent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Agent'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Delete of agent
      tags:
      - Agent
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Agent'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Get of agents
      tags:
      - Agent
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of agent
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Agent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Agent'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Create of agent
      tags:
      - Agent
    put:
      consumes:
      - application/json
      parameters:
      - description: scheme of agent
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Agent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Agent'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Update of agent
      tags:
      - Agent
  /clients:
    delete:
      consumes:
      - application/json
      parameters:
      - description: scheme of client
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Client'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Delete of client
      tags:
      - Client
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Get of clients
      tags:
      - Client
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of client
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Client'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Create of client
      tags:
      - Client
    put:
      consumes:
      - application/json
      parameters:
      - description: scheme of client
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Client'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Client'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorMessage'
      summary: Update of client
      tags:
      - Client
swagger: "2.0"
